import { Timestamp } from "firebase/firestore";

// Generated by https://quicktype.io
// honestly quicktype extension in vscode is great if your not sure of the json objects types

export interface Recipe {
  id: string;
  image: ImageProps;
  recipeName: string;
  recipeDescription: string;
  notes?: string;
  info: Info;
  ingredients: Ingredient[];
  steps: Step[];
  keywords: string[];
  dietary: SelectValue[];
  allergens: SelectValue[];
  sweet_savoury: SelectValue;
  mealTime: SelectValue;
  version: string;
  createdBy: UserInfo;
  createdAt: Timestamp;
  lastUpdated: Timestamp;
  lastUpdatedBy: UserInfo;
  madeRecipe: number;
  savedRecipe: number;
}

export interface SelectValue {
  value: string;
  label: string;
}

export interface Info {
  total: string;
  prep: string;
  cook: string;
  serves: number | undefined;
  rating: number;
}

export interface Step {
  step_body: string;
}

export interface Ingredient {
  ingredient: string;
  unit: string;
  quantity: number | undefined;
  measurement?: string;
}

export interface ImageProps {
  imgUrl: string;
  imgAlt: string;
}

export interface UserInfo {
  uid: string | undefined;
  displayName: string | null | undefined;
  userName: string;
  email?: string | null | undefined;
  phoneNumber?: string | null | undefined;
}
